# Generated by Django 5.2.7 on 2025-10-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_offer_created_at_alter_offer_updated_at'),
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='features',
            field=models.ManyToManyField(related_name='orders', to='offers_app.feature'),
        ),
    ]
