# Generated by Django 5.2.7 on 2025-10-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_remove_offerdetails_features_and_more'),
        ('orders_app', '0002_order_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='offers_app.offerdetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In_Progress'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='in_progress', max_length=50),
        ),
    ]
