# Generated by Django 5.2.7 on 2025-10-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
