# Generated by Django 5.2.7 on 2025-10-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_remove_offerdetails_features_and_more'),
        ('orders_app', '0003_alter_order_offer_detail_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferDetails',
        ),
    ]
