# Generated by Django 5.2.7 on 2025-10-17 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0009_delete_offerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
