# Generated by Django 5.2.7 on 2025-10-17 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0010_offerdetail_created_at_offerdetail_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
