# Generated by Django 5.2.7 on 2025-10-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_at',
        ),
    ]
